# host_vars/ec2/ec2.yml
# ec2 variables


# Red Hat Enterprise Linux version 7.5 (HVM), EBS General Purpose (SSD) Volume Type
instance_type: m4.medium
image: ami-2345234
publisher_count : 2
dispatcher_count : 2
ansible_distribution: Ubuntu
keypair: Swinburne-Admin
