- name: ELB Display all variables/facts known for a host
  debug:
    var: string_var_1

- name: Display host vars
  debug:
    var: vpc_cidr_block

- name: ELB Debug
  debug: msg="Current user name is {{ ansible_ssh_user }}"
  tags:
    - user