- name: EC2 Display all variables/facts known for a host
  debug:
    var: string_var_1

- name: Display sample host vars
  debug:
    msg: Instance Type is {{ instance_type }} with image {{ image }}

- name: EC2 Debug
  debug: msg="Current user name is {{ ansible_ssh_user }}"
  tags:
    - user